---
virtualbox_become_user: "{{ lookup('env','USER') }}"
virtualbox_become_user_home: "{{ lookup('env','HOME') }}"
virtualbox_version: "6.0.4"
virtualbox_extension_checksum: "sha256:8887d5dd9dd26bd376926b38857715e28f2d678b6d3a034144ddc3fde4a387d9"
virtualbox_extension_license: "56be48f923303c8cababb0bb4c478284b688ed23f16d775d729b89a2e8e5f9eb" # This code appears after you accept the license once on the command line.
virtualbox_extension_file: "Oracle_VM_VirtualBox_Extension_Pack-{{ virtualbox_version }}.vbox-extpack"
virtualbox_extension_url: "https://download.virtualbox.org/virtualbox/{{ virtualbox_version }}/{{ virtualbox_extension_file }}"
virtualbox_cache: "{{ lookup('env','HOME') ~ '/Downloads' }}"
