---
- hosts: all
  become: true
  gather_facts: true

- hosts: all
  gather_facts: false
  vars:
    target_user: "{{ lookup('env','USER') }}"
    target_user_home: "{{ lookup('env','HOME') }}"
  roles:
    - role: repositories
      tags:
        - repositories
    - role: packages
      packages_pip_become_user: "{{ target_user }}"
      packages_pip_become_user_home: "{{ target_user_home }}"
      tags:
        - packages
    - role: kvm
      kvm_user: "{{ target_user }}"
    - role: displaylink
      displaylink_become_user: "{{ target_user }}"
      displaylink_become_user_home: "{{ target_user_home }}"
    - role: docker
    - role: asdf
      asdf_become_user: "{{ target_user }}"
      asdf_become_user_home: "{{ target_user_home }}"
    - role: homebrew
      homebrew_become_user: "{{ target_user }}"
      homebrew_become_user_home: "{{ target_user_home }}"
    #- role: nvm
    #  nvm_become_user: "{{ target_user }}"
    #  nvm_become_user_home: "{{ target_user_home }}"
    #- role: pyenv
    #  pyenv_become_user: "{{ target_user }}"
    #  pyenv_become_user_home: "{{ target_user_home }}"
    - role: powerline
      powerline_become_user: "{{ target_user }}"
      powerline_become_user_home: "{{ target_user_home }}"
    - role: vagrant
      vagrant_become_user: "{{ target_user }}"
      vagrant_become_user_home: "{{ target_user_home }}"
    #- role: virtualbox
    #  virtualbox_become_user: "{{ target_user }}"
    #  virtualbox_become_user_home: "{{ target_user_home }}"

- hosts: displaylink
  gather_facts: false
  vars:
    target_user: "{{ lookup('env','USER') }}"
    target_user_home: "{{ lookup('env','HOME') }}"
  roles:
    - role: displaylink
      displaylink_become_user: "{{ target_user }}"
      displaylink_become_user_home: "{{ target_user_home }}"

- hosts: azure
  gather_facts: false
  vars:
    target_user: "{{ lookup('env','USER') }}"
    target_user_home: "{{ lookup('env','HOME') }}"
  roles:
    - role: az-cli-extensions
      az_cli_extensions_user: "{{ target_user }}"
