---
- hosts: all
  become: true
  gather_facts: true
  pre_tasks:
    - name: Variables
      include_vars: vars/main.yml
  tags:
    - always

- hosts: all
  become: true
  gather_facts: false
  roles:
    - role: repositories
      tags:
        - repositories
    - role: packages
      tags:
        - packages
        - packages_apt
    - role: pip
      pip_become_user: "{{ target_user }}"
      pip_become_user_home: "{{ target_user_home }}"
      tags:
        - packages
        - packages_pip
    - role: pipx
      pipx_become_user: "{{ target_user }}"
      pipx_become_user_home: "{{ target_user_home }}"
      tags:
        - packages
        - packages_pipx

- hosts: kvm
  gather_facts: false
  roles:
    - role: kvm
      kvm_user: "{{ target_user }}"
      tags:
        - kvm

- hosts: aws
  gather_facts: false
  roles:
    - role: aws-session-manager
      tags:
        - aws

- hosts: displaylink
  gather_facts: false
  roles:
    - role: displaylink
      displaylink_become_user: "{{ target_user }}"
      displaylink_become_user_home: "{{ target_user_home }}"
      tags:
        - displaylink

- hosts: docker
  gather_facts: false
  roles:
    - role: docker
      docker_target_user: "{{ target_user }}"
      tags:
        - docker

- hosts: asdf
  gather_facts: false
  roles:
    - role: asdf
      asdf_become_user: "{{ target_user }}"
      asdf_become_user_home: "{{ target_user_home }}"
      tags:
        - asdf

- hosts: git
  gather_facts: false
  roles:
    - role: git
      git_become_user: "{{ target_user }}"
      git_become_user_home: "{{ target_user_home }}"
      tags:
        - git

- hosts: gpgme
  gather_facts: false
  roles:
    - role: gpgme
      gpgme_become_user: "{{ target_user }}"
      gpgme_become_user_home: "{{ target_user_home }}"
      tags:
        - gpgme

- hosts: homebrew
  gather_facts: false
  roles:
    - role: homebrew
      homebrew_become_user: "{{ target_user }}"
      homebrew_become_user_home: "{{ target_user_home }}"
      tags:
        - homebrew

- hosts: sdkman
  gather_facts: false
  roles:
    - role: sdkman
      sdkman_become_user: "{{ target_user }}"
      sdkman_become_user_home: "{{ target_user_home }}"
      tags:
        - sdkman

- hosts: nvm
  gather_facts: false
  roles:
    - role: nvm
      nvm_become_user: "{{ target_user }}"
      nvm_become_user_home: "{{ target_user_home }}"
      tags:
        - nvm

- hosts: pyenv
  gather_facts: false
  roles:
    - role: pyenv
      pyenv_become_user: "{{ target_user }}"
      pyenv_become_user_home: "{{ target_user_home }}"
      tags:
        - pyenv

- hosts: powerline
  gather_facts: false
  roles:
    - role: powerline
      powerline_become_user: "{{ target_user }}"
      powerline_become_user_home: "{{ target_user_home }}"
      tags:
        - powerline

- hosts: vagrant
  gather_facts: false
  roles:
    - role: vagrant
      vagrant_become_user: "{{ target_user }}"
      vagrant_become_user_home: "{{ target_user_home }}"
      tags:
        - vagrant

- hosts: virtualbox
  gather_facts: false
  roles:
    - role: virtualbox
      virtualbox_become_user: "{{ target_user }}"
      virtualbox_become_user_home: "{{ target_user_home }}"
      tags:
        - virtualbox

- hosts: azure
  gather_facts: false
  roles:
    - role: azure-cli
      azure_cli_become_user: "{{ target_user }}"
      azure_cli_become_user_home: "{{ target_user_home }}"
      tags:
        - azure

- hosts: zoom
  gather_facts: false
  roles:
    - role: zoom
      zoom_become_user: "{{ target_user }}"
      zoom_become_user_home: "{{ target_user_home }}"
      tags:
        - zoom
