---
- hosts: all
  become: true
  gather_facts: true

- hosts: all
  gather_facts: false
  vars:
    target_user: "{{ lookup('env','USER') }}"
    target_user_home: "{{ lookup('env','HOME') }}"
  roles:
    - repositories
    - role: packages
      packages_pip_become_user: "{{ target_user }}"
      packages_pip_become_user_home: "{{ target_user_home }}"
    - role: kvm
      kvm_user: "{{ target_user }}"
    - role: docker
    - role: nvm
      nvm_become_user: "{{ target_user }}"
      nvm_become_user_home: "{{ target_user_home }}"
    - role: pyenv
      pyenv_become_user: "{{ target_user }}"
      pyenv_become_user_home: "{{ target_user_home }}"
    - role: powerline
      powerline_become_user: "{{ target_user }}"
      powerline_become_user_home: "{{ target_user_home }}"
    - role: vagrant
      vagrant_become_user: "{{ target_user }}"
      vagrant_become_user_home: "{{ target_user_home }}"
    #- role: virtualbox
    #  virtualbox_become_user: "{{ target_user }}"
    #  virtualbox_become_user_home: "{{ target_user_home }}"
