---
- name: Install pre-packages
  become: true
  apt:
    name: "{{ packages_apt_pre }}"
    state: present
  when: (ansible_facts['os_family'] | lower) == 'debian'

- name: Pre-configure Packages
  become: true
  debconf:
    name: "{{ item.name }}"
    question: "{{ item.question | default(omit) }}"
    value: "{{ item.value | default(omit) }}"
    vtype: "{{ item.vtype | default(omit) }}"
  when: (ansible_facts['os_family'] | lower) == 'debian'
  loop: "{{ packages_apt_debconf }}"

- name: Install packages
  become: true
  apt:
    name: "{{ packages_apt }}"
    state: present
  when: (ansible_facts['os_family'] | lower) == 'debian'

- name: Install pip user packages
  become: true
  become_user: "{{ packages_become_user }}"
  pip:
    name: "{{ packages_pip_user }}"
    executable: "{{ packages_pip_executable | default(omit) }}"
    extra_args: --user
    state: present
