---
# Insecure registry is for minikube
docker_daemon_config:
  "insecure-registries":
    - "192.168.39.0/24"
  "storage-driver": overlay2
docker_daemon_listeners:
  - fd://
  - tcp://127.0.0.1:2375
docker_service_enable: true
docker_service_state: started
