---
- name: Add powerline to vim
  become: true
  become_user: "{{ powerline_become_user }}"
  command: /usr/bin/vim-addons install powerline
  args:
    creates: "{{ powerline_become_user_home ~ '/.vim/plugin/powerline.vim' }}"

- name: Enable and Start Powerline Daemon
  become: true
  become_user: "{{ powerline_become_user }}"
  systemd:
    name: powerline-daemon.service
    enabled: true
    state: started
    scope: user
