---
homebrew_taps: "{{ dict(hostvars[inventory_hostname]) | default({}) | key_startswith('homebrew_taps__') | list | default([]) | flatten(levels=1) | unique }}"
homebrew_formulae: "{{ dict(hostvars[inventory_hostname]) | default({}) | key_startswith('homebrew_formulae__') | list | default([]) | flatten(levels=1) | sort | unique }}"
