---
homebrew_taps: "{{ query('varnames', '^homebrew_taps__.+') | map('extract', hostvars[inventory_hostname]) | list | flatten(levels=1) | unique }}"
homebrew_formulae: "{{ query('varnames', '^homebrew_formulae__.+') | map('extract', hostvars[inventory_hostname]) | list | flatten(levels=1) | unique }}"
