---
packages_apt_debconf: "{{ query('varnames', '^packages_apt_debconf__.+') | map('extract', hostvars[inventory_hostname]) | list | flatten(levels=1) | sort | unique }}"
packages_apt: "{{ query('varnames', '^packages_apt__.+') | map('extract', hostvars[inventory_hostname]) | list | flatten(levels=1) | sort | unique }}"

packages_pip_user: "{{ query('varnames', '^packages_pip_user__.+') | map('extract', hostvars[inventory_hostname]) | list | flatten(levels=1) | sort | unique }}"
