---
packages_apt__pip:
  - python3-dev
  - python3-pip
  - python3-venv

pip_packages_user: "{{ query('varnames', '^pip_packages_user__.+') | map('extract', hostvars[inventory_hostname]) | list | flatten(levels=1) | sort | unique }}"
