---
repositories_apt_pre: "{{ query('varnames', '^repositories_apt_pre__.+') | map('extract', hostvars[inventory_hostname]) | list | flatten(levels=1) | unique }}"
repositories_apt_key: "{{ query('varnames', '^repositories_apt_key__.+') | map('extract', hostvars[inventory_hostname]) | list | flatten(levels=1) | unique }}"
repositories_apt: "{{ query('varnames', '^repositories_apt__.+') | map('extract', hostvars[inventory_hostname]) | list | flatten(levels=1) | unique }}"
