---
packages_apt__pyenv:
  - build-essential
  - curl
  - git
  - libbz2-dev
  - libffi-dev
  - liblzma-dev
  - libncurses5-dev
  - libncursesw5-dev
  - libreadline-dev
  - libsqlite3-dev
  - libssl-dev
  - llvm
  - make
  - python-openssl
  - python3-openssl
  - tk-dev
  - wget
  - xz-utils
  - zlib1g-dev
