---
repositories_apt_key__docker:
  - url: https://download.docker.com/linux/ubuntu/gpg
    id: '9DC858229FC7DD38854AE2D88D81803C0EBFCD88'

repositories_apt__docker:
  - filename: docker
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_facts['distribution_release'] }} stable"

repositories_apt_pre__docker:
  - 'apt-transport-https'
  - 'ca-certificates'
  - 'curl'
  - 'gnupg-agent'
  - 'software-properties-common'

packages_apt__docker:
  - 'docker-ce'
  - 'docker-ce-cli'
  - 'containerd.io'
