---
repositories_apt_key__docker:
  - url: https://download.docker.com/linux/ubuntu/gpg
    id: '9DC858229FC7DD38854AE2D88D81803C0EBFCD88'

repositories_apt__docker:
  - filename: docker
    # No focal repo at present, use eoan
    #repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_facts['distribution_release'] }} stable"
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu eoan stable"

repositories_apt_pre__docker:
  - 'apt-transport-https'
  - 'ca-certificates'
  - 'curl'
  - 'gnupg-agent'
  - 'jq'
  - 'software-properties-common'

packages_apt__docker:
  - 'docker-ce'
  - 'docker-ce-cli'
  - 'containerd.io'

asdf_plugins__docker:
  - name: docker-compose
    url: https://github.com/virtualstaticvoid/asdf-docker-compose.git
