---
repositories_apt_key__azure_cli:
  - url: https://packages.microsoft.com/keys/microsoft.asc
    id: 'BC528686B50D79E339D3721CEB3E94ADBE1229CF'
    keyring: /etc/apt/trusted.gpg.d/microsoft-prod.gpg

repositories_apt__azure_cli:
  - filename: azure-cli
    # No focal repo at present, use bionic instead
    #repo: 'deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ {{ ansible_lsb["codename"] | lower }} main'
    repo: 'deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ bionic main'

packages_apt__azure_cli:
  - 'azure-cli'

azure_cli_extensions:
  - 'azure-devops'
  - 'aks-preview'
