---
asdf_plugins__kubernetes:
  - name: helm
    versions:
      - '2.14.3'
    global: '2.14.3'
  - name: kops
    versions:
      - '1.14.0.beta.2'
    global: '1.14.0.beta.2'
  - name: kubectl
    versions:
      - '1.15.3'
    global: '1.15.3'
  - name: minikube
    versions:
      - '1.3.1'
    global: '1.3.1'
