---
# az should be installed by the "repos" and "packages" roles - this is about cli extensions

- name: retrieve available extensions
  become: true
  become_user: "{{ az_cli_extensions_become_user }}"
  command: az extension list-available --output json
  changed_when: false
  check_mode: false
  register: _extension_list_all_raw

- name: extension facts from JSON via CLI
  set_fact:
    _extension_list_all: "{{ _extension_list_all_raw.stdout | from_json }}"

- name: extension facts
  set_fact:
    _extension_list_install: "{{ _extension_list_install |
      default([]) |
      union( [item['name']] if item['name'] in az_cli_extensions and not item['installed'] else [] )
    }}"
  loop: "{{ _extension_list_all }}"

- debug:
    var: az_cli_extensions
- debug:
    var: _extension_list_install

- name: install extensions
  become: true
  become_user: "{{ az_cli_extensions_become_user }}"
  command: "az extension add --output json --yes --name {{ item }}"
  loop: "{{ _extension_list_install }}"
  tags:
    - skip_ansible_lint
